name: default
components:
  S: 1.0
  C: 0.3
  E: -0.1
  Sharpe: 0.2
  LookbackPenalty: -0.2
params:
  edge:
    edge_boundary: 1.0
    penalty_same: 0.2
    jump_threshold: 10
    delta_weight: 0.0
  sharpe:
    min_vol: 1.0e-6
  lookback:
    target: null
    width: 0.5
