name: sac
library: sb3
policy: ${policy_arch.class_name}
policy_architecture: ${policy_arch.name}
policy_kwargs: ${policy_arch.kwargs}
hyperparams:
  buffer_size: 1000000
  learning_rate: 0.0003
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  train_freq: 1
  gradient_steps: 1
  ent_coef: auto
