extends: ../base.yaml

run:
  run_name: rl_ppo

analysis:
  method: signature
  lookback: 60
  update_freq: 1
  signature:
    sig_method: levy

rl:
  min_lookback: 10
  max_lookback: 120
  discrete_actions: true
  action_mode: hybrid
  relative_step: 5
  episode_length: 252
  random_start: true
  ema_alpha: 0.2
  policy: attention
  policy_kwargs:
    features_extractor_kwargs:
      features_dim: 96
      n_heads: 4
  total_timesteps: 50000
  n_steps: 512
  batch_size: 256
  learning_rate: 0.0003
  gamma: 0.99
  ent_coef: 0.0
  eval_freq: 0
  verbose: false
  reward_weights:
    alpha: 1.0
    beta: 0.3
    gamma: 0.08
  penalty_same: 0.05
  penalty_step: 10
