"""Helpers for validating the paper artefact set."""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, Sequence

REQUIRED_PAPER_ARTIFACTS: Sequence[str] = (
    "main_results.csv",
    "ablations.csv",
    "hac_sharpe_ci.csv",
    "psr_dsr_pvalues.csv",
    "spa_table.csv",
    "mcs_table.csv",
    "forest.png",
    "heatmap.png",
    "pnl.png",
    "report.html",
)


def validate_paper_artifact_set(
    out_dir: Path | str,
    *,
    required: Iterable[str] | None = None,
) -> list[Path]:
    """Ensure that the expected paper artefacts exist under ``out_dir``.

    Parameters
    ----------
    out_dir:
        Directory containing the artefacts generated by ``reproduce_all.sh``.
    required:
        Optional override for the filenames that must exist.

    Returns
    -------
    list[Path]
        Paths to the validated artefacts. A :class:`FileNotFoundError` is raised
        if any expected file is missing.
    """

    directory = Path(out_dir)
    if not directory.exists():
        raise FileNotFoundError(f"Paper artefact directory {directory} does not exist")

    expected = list(required) if required is not None else list(REQUIRED_PAPER_ARTIFACTS)
    missing: list[str] = []
    resolved: list[Path] = []
    for name in expected:
        candidate = directory / name
        if candidate.exists():
            resolved.append(candidate)
        else:
            missing.append(name)
    if missing:
        formatted = ", ".join(sorted(missing))
        raise FileNotFoundError(f"Missing paper artefacts: {formatted}")
    return resolved


__all__ = ["REQUIRED_PAPER_ARTIFACTS", "validate_paper_artifact_set"]
