extends: rl_ppo.yaml

run:
  run_name: rl_ppo_lstm

rl:
  policy: ppo_lstm
  policy_kwargs:
    lstm_hidden_size: 128
    enable_critic_lstm: true
  total_timesteps: 60000
  n_steps: 256
  batch_size: 128
