run:
  output_root: results
  run_name: auto
  seed: 42

data:
  price_csv: raw_data/daily_price.csv
  # Optional: universe CSV if available; set to null to ignore
  universe_csv: null

analysis:
  method: signature
  lookback: 30
  update_freq: 1
  use_parallel: false
  num_cpus: 4
  show_progress: false
  Scaling_Method: mean-centering
  ccf_at_lag:
    lag: 1
    correlation_method: pearson
    quantiles: 4
  signature:
    sig_method: levy
    correlation_method: pearson
    quantiles: 4

metrics:
  compute:
    - mean_abs_matrix
    - max_abs_matrix
    - row_sum_range
    - row_sum_std
    - stability_matrix_corr
    - stability_rowsum_corr
  headless: false
  plots:
    - signal_strength
    - stability
